remote-week2: initial commit
yingyinglininin/remote-assignments pull request #2
Opened 2023-10-11 15:49 UTC by yingyinglininin

IP address can access to my APIs: 13.215.241.188 
- app.js: port 4000
- adminAPI.js: port 3000

Database name: http://database-1.c8of2lxxr8vl.ap-southeast-1.rds.amazonaws.com/
Change summary:
- Create assignment.user table in MySQL
- Add app.js
- Add adminAPI.js

Understanding Check:
1. I have created a user table according to the specifications outlined in assignment 2. I've designated the 'id' column as the primary key and set the other columns with appropriate data types and default values. Here's the schema for the user table: <img width="815" alt="image" src="https://github.com/yingyinglininin/remote-assignments/assets/130786876/530acfe9-afe3-4c74-93a3-c10ca53e9b44"> <img width="815" alt="image" src="https://github.com/yingyinglininin/remote-assignments/assets/130786876/f1d2dc0f-71a9-44f7-81cf-257bfe37424a">
2. Status code is standardized three-digit numbers returned by an API in response to a client’s request to indicate the outcome of a specific HTTP request. The common HTTP status codes include: 200 (OK), 403 (Forbidden), 404 (Not Found). 
The following is the HTTP Status Code part of Restful API document: https://restfulapi.net/http-status-codes/ 
It is not mandatory for all APIs, but it’s highly recommended to use because it enhances the usability and reliability of our APIs. We can quickly know the status of our client requests and determine the nature of the error.
3. After developing our APIs, we can use some tools such as Postman (test directly in GUI) and Swagger (Write Swagger document) to test our APIs. We can start our backend service in localhost or deploy it on cloud servers such as Amazon EC2. Next, use the client (API testing tools) to send the request with an API URL. Finally, we can get the status code and the response data from the server.
4. Firstly, we can enter EC2 with an ssh connection. Next, we can use commands such as `screen`, `tmux` and `nohup` to keep remote SSH sessions and processes running after disconnection.
![image](https://github.com/yingyinglininin/remote-assignments/assets/130786876/b71fb379-4056-4227-928d-a84b6bf9d270)
![image](https://github.com/yingyinglininin/remote-assignments/assets/130786876/67da0b77-970a-4928-a39c-9b0b88225428)
![image](https://github.com/yingyinglininin/remote-assignments/assets/130786876/302d9cc9-81b0-4d96-9d19-1bb5ab50d9a8)

5. The following is the interation diagram between client, firewall, EC2 instance and RDS database: <img width="896" alt="image" src="https://github.com/yingyinglininin/remote-assignments/assets/130786876/d728b661-19f4-43c3-ac41-a8cfb672afca">

6. To allow clients to access APIs without specifying a port number in the URL, we can use standard ports. That is, web applications typically run on HTTP (port 80) or HTTPS (port 443) by default. By using these standard ports, we can omit the port number from the URL. However, we will encounter an error message "permission denied 0.0.0.0:443" because we need root permissions to access port < 1024. Thus, using ngnix as a reverse proxy server may be a solution. (To be researched) <img width="894" alt="image" src="https://github.com/yingyinglininin/remote-assignments/assets/130786876/69f581cd-2bbd-4ec2-8794-063e25d0bb2f">
- Stack Overflow: https://stackoverflow.com/questions/50112186/error-listen-eacces-0-0-0-0443
- Setup Nginx as reverse proxy on EC2 instance: https://medium.com/@imageadhikari/setup-nginx-as-reverse-proxy-on-ec2-instance-3c6820b6467b
7. A web server is a software component that delivers static data such as images, files, and in response to client requests. An application server adds business logic to compute the web server's response. In summary, a web server only hosts websites and delivers responses to simple requests. On the other hand, application servers handle business logic to generate dynamic content by connecting with enterprise systems, services and databases.

2023-10-11 16:53 UTC, addie-tyc requested changes
understanding check 很完整～小地方需修正

2023-10-11 16:53 UTC, addie-tyc commented on Week2/adminAPI.js
> +const bodyParser = require('body-parser');
現在用的 express 版本還有需要引入 body-parser 嗎？

2023-10-11 16:53 UTC, addie-tyc commented on Week2/adminAPI.js
> +                  "request-date": new Date().toUTCString()
request-date 是要直接從 request header 拿對應的 key 喔

2023-10-11 16:53 UTC, addie-tyc commented on Week2/adminAPI.js
> +              "request-date": new Date().toUTCString()
同上

2023-10-11 17:00 UTC, addie-tyc commented
healthcheck 好像沒有對外開放？

2023-10-13 13:31 UTC, addie-tyc requested changes
healthcheck OK，但 user 好像壞了？
<img width="1000" alt="截圖 2023-10-13 21 31 47" src="https://github.com/yingyinglininin/remote-assignments/assets/65952631/4141cf93-46cb-4bb8-92bc-9125fc4695fc">

2023-10-13 14:00 UTC, yingyinglininin commented on Week2/adminAPI.js
> +const bodyParser = require('body-parser');
因為之前在嘗試 `app.use(body-parser.json());` 的語法，以為需要導入 body-parser 才可以，不過研究後發現，現在的版本直接使用`app.use(express.json());` 即可

2023-10-13 14:00 UTC, yingyinglininin commented on Week2/adminAPI.js
> +                  "request-date": new Date().toUTCString()
Done

2023-10-13 14:00 UTC, yingyinglininin commented on Week2/adminAPI.js
> +              "request-date": new Date().toUTCString()
Done

2023-10-13 14:02 UTC, yingyinglininin commented
> healthcheck 好像沒有對外開放？

先前因為沒有在 EC2 開啟對應的 port 4000 權限，所以沒有對外開放，目前已經順利開啟！

2023-10-13 14:05 UTC, yingyinglininin commented
> healthcheck OK，但 user 好像壞了？ <img alt="截圖 2023-10-13 21 31 47" width="1000" src="https://user-images.githubusercontent.com/65952631/274915384-4141cf93-46cb-4bb8-92bc-9125fc4695fc.png">

剛剛發現是因為少了` app.use(express.json()); ` 所以導致在 post api 會壞掉，目前加上後已經可以順利使用！

2023-10-14 05:52 UTC, merged

2023-10-14 10:56 UTC, addie-tyc commented
LGTM